### ISSUE TITLE
Install with zef depends on Informative but it is not listed in "depends" in META6

### ISSUE THREAD

**Issue by thundergnat** [finanalyst/raku-pod-render#4]
```
===> Install [FAIL] for Raku::Pod::Render:ver<2.3.1>:auth<github:finanalyst>: ===SORRY!=== Error while compiling /home/steve/mygit/site#sources/AD872D1014CE395488BFEAEE0A982E1E928078EA (read-y-me.raku)
Could not find Informative in:
    inst#/home/steve/.perl6/share/perl6/site
    inst#/home/steve/.perl6/share/perl6/vendor
    inst#/home/steve/.perl6/share/perl6/core
    ap#
    nqp#
    perl5#
at /home/steve/mygit/site#sources/AD872D1014CE395488BFEAEE0A982E1E928078EA (read-y-me.raku):22
```

Installs ok when I manually install Informative before trying to install.

**Comment by antoniogamiz** [comment]
Same problem here.

**Comment by finanalyst** [comment]
I deliberately left Informative out of the depends, so that zef would not try to install it!!!!!

But zef has done so anyway. It is not in the tests. @*$#@($@#($*@#($$&

The reason is that Informative does not install in Windows.

I will change this to a dependency to GTK::Simple. (First I will need to refactor read-y-me. It will work as a CLI program)
