### ISSUE TITLE
How can I use my own mustache template?

### ISSUE THREAD

**Issue by antoniogamiz** [finanalyst/raku-pod-render#5]
I would like to something like:
~~~raku
use Pod::Load;
use Pod::To::HTML;

my $pod = load("Endian.pod6")[0];

my $processor = Pod::To::HTML.new(:templates("main.mustache"));

say $processor.render($pod);
~~~
Is this possible? After reading the [docs](https://github.com/finanalyst/raku-pod-render/blob/master/Pod2HTML.md#custom-pod-and-template) I'm not sure.

**Comment by antoniogamiz** [comment]
Ah, I suppose I have to override this template?
https://github.com/finanalyst/raku-pod-render/blob/2cd4ce24ceb45e8c118a7fe8267a37b6a7659e2e/lib/Pod/To/HTML.pm6#L204-L222

**Comment by finanalyst** [comment]
Yes. It is possible.

Yes, that is the template to over-ride.

**Comment by finanalyst** [comment]
But I would suggest to over-ride 'head-block' to include the custom head information.

**Comment by antoniogamiz** [comment]
Hum, that makes sense. I will make some tests later today. Thanks for your help :)

**Comment by finanalyst** [comment]
Sorry, I misread the question
`my $processor = Pod::To::HTML.new(:templates("main.mustache"));`
will fail. That is because `tempates` is expecting either a hash of all the templates needed, or the name of a raku program
that will generate all the templates in a hash. 

But if `html-templates.raku` exists in the current working directory, then this will be automatically loaded.

This is all documented in Pod2HTML and RenderPod
